// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB4cwPoPVeb7GUmdTBOLNt1NcvpLF68tgg',
//     appId: '1:84765251346:web:dc183788658da82e0785cb',
//     messagingSenderId: '84765251346',
//     projectId: 'kumbu-server',
//     authDomain: 'kumbu-server.firebaseapp.com',
//     storageBucket: 'kumbu-server.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC1gN-P2zhYLH0SneolEw3Kv-IJyzKQHEA',
//     appId: '1:84765251346:android:5ab811c9f6ff15910785cb',
//     messagingSenderId: '84765251346',
//     projectId: 'kumbu-server',
//     storageBucket: 'kumbu-server.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAlrnL9imQYcO_jox9t87y8xC3rFYi3ESU',
//     appId: '1:84765251346:ios:6e104363c9a0169b0785cb',
//     messagingSenderId: '84765251346',
//     projectId: 'kumbu-server',
//     storageBucket: 'kumbu-server.appspot.com',
//     androidClientId: '84765251346-sjmndesqautddegan1iue8qci5ostojl.apps.googleusercontent.com',
//     iosClientId: '84765251346-hbupa3a89befdeisd23gmr2l9ohn1t6o.apps.googleusercontent.com',
//     iosBundleId: 'com.example.kumbuAdmin',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAlrnL9imQYcO_jox9t87y8xC3rFYi3ESU',
//     appId: '1:84765251346:ios:6e104363c9a0169b0785cb',
//     messagingSenderId: '84765251346',
//     projectId: 'kumbu-server',
//     storageBucket: 'kumbu-server.appspot.com',
//     androidClientId: '84765251346-sjmndesqautddegan1iue8qci5ostojl.apps.googleusercontent.com',
//     iosClientId: '84765251346-hbupa3a89befdeisd23gmr2l9ohn1t6o.apps.googleusercontent.com',
//     iosBundleId: 'com.example.kumbuAdmin',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB4cwPoPVeb7GUmdTBOLNt1NcvpLF68tgg',
//     appId: '1:84765251346:web:6fd3c7a648a194e90785cb',
//     messagingSenderId: '84765251346',
//     projectId: 'kumbu-server',
//     authDomain: 'kumbu-server.firebaseapp.com',
//     storageBucket: 'kumbu-server.appspot.com',
//   );
// }
