import 'package:flutter/material.dart';
import 'package:kumbu_admin/Common/ThemeData.dart';

import 'Models/Member.dart';
import 'Screens/MembersListPage.dart';

void main() {
  List<GymMember> members = [
    GymMember(
      id: '1',
      name: 'Alice',
      age: 28,
      gender: 'Female',
      currentPackageID: 'p1',
      membershipDuration: '2 year',
      membershipStartDate: DateTime(2023, 1, 1),
      membershipEndDate: DateTime(2025, 1, 1),
      level: MembershipLevel.GOLD,
      email: 'alice@example.com',
      phoneNumber: '123-456-7890',
      address: '123 Main St, Anytown, USA',
      isActive: true,
      purchaseOrderHistories: ['po1', 'po2'],
      dietID: 'd1',
      daysAttended: 100,
    ),
    GymMember(
      id: '2',
      name: 'Bob',
      age: 34,
      gender: 'Male',
      currentPackageID: 'p2',
      membershipDuration: '1 month',
      membershipStartDate: DateTime(2024, 6, 10),
      membershipEndDate: DateTime(2024, 7, 10),
      level: MembershipLevel.SILVER,
      email: 'bob@example.com',
      phoneNumber: '098-765-4321',
      address: '456 Elm St, Othertown, USA',
      isActive: true,
      purchaseOrderHistories: ['po3'],
      dietID: 'd2',
      daysAttended: 20,
    ),
    GymMember(
      id: '3',
      name: 'Charlie',
      age: 22,
      gender: 'Male',
      currentPackageID: 'p3',
      membershipDuration: '1 year',
      membershipStartDate: DateTime(2024, 2, 1),
      membershipEndDate: DateTime(2025, 2, 1),
      level: MembershipLevel.BRONZE,
      email: 'charlie@example.com',
      phoneNumber: '123-123-1234',
      address: '789 Oak St, Somewhere, USA',
      isActive: true,
      purchaseOrderHistories: [],
      dietID: 'd3',
      daysAttended: 50,
    ),
    GymMember(
      id: '4',
      name: 'David',
      age: 45,
      gender: 'Male',
      currentPackageID: 'p4',
      membershipDuration: '1 month',
      membershipStartDate: DateTime(2023, 3, 15),
      membershipEndDate: DateTime(2023, 4, 15),
      level: MembershipLevel.SILVER,
      email: 'david@example.com',
      phoneNumber: '321-654-0987',
      address: '101 Maple St, Anytown, USA',
      isActive: false,
      purchaseOrderHistories: ['po4'],
      dietID: 'd4',
      daysAttended: 10,
    ),
    GymMember(
      id: '5',
      name: 'Eve',
      age: 29,
      gender: 'Female',
      currentPackageID: 'p5',
      membershipDuration: '1 year',
      membershipStartDate: DateTime(2024, 4, 1),
      membershipEndDate: DateTime(2025, 4, 1),
      level: MembershipLevel.GOLD,
      email: 'eve@example.com',
      phoneNumber: '456-789-1230',
      address: '202 Pine St, Othertown, USA',
      isActive: true,
      purchaseOrderHistories: [],
      dietID: 'd5',
      daysAttended: 70,
    ),
    GymMember(
      id: '6',
      name: 'Frank',
      age: 38,
      gender: 'Male',
      currentPackageID: 'p6',
      membershipDuration: '1 year',
      membershipStartDate: DateTime(2023, 1, 10),
      membershipEndDate: DateTime(2024, 1, 10),
      level: MembershipLevel.BRONZE,
      email: 'frank@example.com',
      phoneNumber: '789-012-3456',
      address: '303 Cedar St, Somewhere, USA',
      isActive: false,
      purchaseOrderHistories: ['po5'],
      dietID: 'd6',
      daysAttended: 30,
    ),
    GymMember(
      id: '7',
      name: 'Grace',
      age: 27,
      gender: 'Female',
      currentPackageID: 'p7',
      membershipDuration: '1 month',
      membershipStartDate: DateTime(2023, 6, 5),
      membershipEndDate: DateTime(2023, 7, 5),
      level: MembershipLevel.SILVER,
      email: 'grace@example.com',
      phoneNumber: '654-321-7890',
      address: '404 Birch St, Anytown, USA',
      isActive: false,
      purchaseOrderHistories: [],
      dietID: 'd7',
      daysAttended: 5,
    ),
    GymMember(
      id: '8',
      name: 'Hank',
      age: 33,
      gender: 'Male',
      currentPackageID: 'p8',
      membershipDuration: '1 month',
      membershipStartDate: DateTime(2023, 5, 20),
      membershipEndDate: DateTime(2023, 6, 20),
      level: MembershipLevel.SILVER,
      email: 'hank@example.com',
      phoneNumber: '321-789-6540',
      address: '505 Spruce St, Othertown, USA',
      isActive: false,
      purchaseOrderHistories: ['po6'],
      dietID: 'd8',
      daysAttended: 15,
    ),
    GymMember(
      id: '9',
      name: 'Ivy',
      age: 26,
      gender: 'Female',
      currentPackageID: 'p9',
      membershipDuration: '1 year',
      membershipStartDate: DateTime(2023, 2, 25),
      membershipEndDate: DateTime(2024, 2, 25),
      level: MembershipLevel.GOLD,
      email: 'ivy@example.com',
      phoneNumber: '987-654-3210',
      address: '606 Redwood St, Somewhere, USA',
      isActive: true,
      purchaseOrderHistories: ['po7', 'po8'],
      dietID: 'd9',
      daysAttended: 90,
    ),
    GymMember(
      id: '10',
      name: 'Jack',
      age: 40,
      gender: 'Male',
      currentPackageID: 'p10',
      membershipDuration: '1 year',
      membershipStartDate: DateTime(2023, 3, 30),
      membershipEndDate: DateTime(2024, 3, 30),
      level: MembershipLevel.PLATINUM,
      email: 'jack@example.com',
      phoneNumber: '456-123-7890',
      address: '707 Willow St, Anytown, USA',
      isActive: true,
      purchaseOrderHistories: [],
      dietID: 'd10',
      daysAttended: 80,
    ),
  ];

  runApp(MaterialApp(
    theme: appTheme,
    home: MembersListPage(members: members),
  ));
}
