import 'package:flutter/material.dart';
import 'package:kumbu_admin/Common/ThemeData.dart';

import 'Models/Member.dart';
import 'Screens/MembersListPage.dart';

void main() {
  List<GymMember> members = [
    GymMember(
      id: '1',
      name: 'Alice',
      age: 28,
      gender: 'Female',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 1, 1),
      membershipEndDate: DateTime(2024, 1, 1),
      membershipDuration: '1 year',
      email: 'alice@example.com',
      phoneNumber: '123-456-7890',
      address: '123 Main St, Anytown, USA',
    ),
    GymMember(
      id: '2',
      name: 'Bob',
      age: 34,
      gender: 'Male',
      membershipType: 'Monthly',
      membershipStartDate: DateTime(2023, 5, 10),
      membershipEndDate: DateTime(2023, 6, 10),
      membershipDuration: '1 month',
      email: 'bob@example.com',
      phoneNumber: '098-765-4321',
      address: '456 Elm St, Othertown, USA',
    ),
    GymMember(
      id: '3',
      name: 'Charlie',
      age: 22,
      gender: 'Male',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 2, 1),
      membershipEndDate: DateTime(2024, 2, 1),
      membershipDuration: '1 year',
      email: 'charlie@example.com',
      phoneNumber: '123-123-1234',
      address: '789 Oak St, Somewhere, USA',
    ),
    GymMember(
      id: '4',
      name: 'David',
      age: 45,
      gender: 'Male',
      membershipType: 'Monthly',
      membershipStartDate: DateTime(2023, 3, 15),
      membershipEndDate: DateTime(2023, 4, 15),
      membershipDuration: '1 month',
      email: 'david@example.com',
      phoneNumber: '321-654-0987',
      address: '101 Maple St, Anytown, USA',
    ),
    GymMember(
      id: '5',
      name: 'Eve',
      age: 29,
      gender: 'Female',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 4, 1),
      membershipEndDate: DateTime(2024, 4, 1),
      membershipDuration: '1 year',
      email: 'eve@example.com',
      phoneNumber: '456-789-1230',
      address: '202 Pine St, Othertown, USA',
    ),
    GymMember(
      id: '6',
      name: 'Frank',
      age: 38,
      gender: 'Male',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 1, 10),
      membershipEndDate: DateTime(2024, 1, 10),
      membershipDuration: '1 year',
      email: 'frank@example.com',
      phoneNumber: '789-012-3456',
      address: '303 Cedar St, Somewhere, USA',
    ),
    GymMember(
      id: '12',
      name: 'Fasil',
      age: 38,
      gender: 'Male',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 1, 10),
      membershipEndDate: DateTime(2024, 1, 10),
      membershipDuration: '1 year',
      email: 'frank@example.com',
      phoneNumber: '789-012-3456',
      address: '303 Cedar St, Somewhere, USA',
    ),
    GymMember(
      id: '7',
      name: 'Grace',
      age: 27,
      gender: 'Female',
      membershipType: 'Monthly',
      membershipStartDate: DateTime(2023, 6, 5),
      membershipEndDate: DateTime(2023, 7, 5),
      membershipDuration: '1 month',
      email: 'grace@example.com',
      phoneNumber: '654-321-7890',
      address: '404 Birch St, Anytown, USA',
    ),
    GymMember(
      id: '8',
      name: 'Hank',
      age: 33,
      gender: 'Male',
      membershipType: 'Monthly',
      membershipStartDate: DateTime(2023, 5, 20),
      membershipEndDate: DateTime(2023, 6, 20),
      membershipDuration: '1 month',
      email: 'hank@example.com',
      phoneNumber: '321-789-6540',
      address: '505 Spruce St, Othertown, USA',
    ),
    GymMember(
      id: '9',
      name: 'Ivy',
      age: 26,
      gender: 'Female',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 2, 25),
      membershipEndDate: DateTime(2024, 2, 25),
      membershipDuration: '1 year',
      email: 'ivy@example.com',
      phoneNumber: '987-654-3210',
      address: '606 Redwood St, Somewhere, USA',
    ),
    GymMember(
      id: '10',
      name: 'Jack',
      age: 40,
      gender: 'Male',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 3, 30),
      membershipEndDate: DateTime(2024, 3, 30),
      membershipDuration: '1 year',
      email: 'jack@example.com',
      phoneNumber: '456-123-7890',
      address: '707 Willow St, Anytown, USA',
    ),
    GymMember(
      id: '11',
      name: 'Jhon',
      age: 40,
      gender: 'Male',
      membershipType: 'Annual',
      membershipStartDate: DateTime(2023, 3, 30),
      membershipEndDate: DateTime(2024, 3, 30),
      membershipDuration: '1 year',
      email: 'jack@example.com',
      phoneNumber: '456-123-7890',
      address: '707 Willow St, Anytown, USA',
    ),
  ];

  runApp(MaterialApp(
    theme: appTheme,
    home: MembersListPage(members: members),
  ));
}


